name: Deploy Database Migrations

on:
  push:
    branches: [main]
    paths:
      - 'supabase/migrations/**'
      - '.github/workflows/supabase-migrations-deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase project
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_REF

      - name: Repair migration history (if needed)
        run: |
          # Repair migration history to handle deleted migration files
          supabase migration repair --status reverted 20240905000001 20240905000002 20240905000003 20240905000004 20240905000005 20240905000006 || echo "Migration repair attempted"
          
      - name: Push database migrations
        run: |
          supabase db push
          
      - name: Verify migrations
        run: |
          echo "Migrations applied successfully to project: $SUPABASE_PROJECT_REF"